spring:
  application:
    name: ColorToMQTTApp
  devtools:
    restart:
      enabled: true
  web:
    resources:
      static-locations: classpath:/static/
app:
  defaultSettings:
    screenHeight: 400
    screenWight: 400
    updatePeriod: 10 #ms
    processor: ru.mkilord.colortomqttapp.core.processor.ChessProcessor
    detector: ru.mkilord.colortomqttapp.core.detector.AverageColorDetector
    screenAreaType: ru.mkilord.colortomqttapp.core.screenshoter.screenArea.DefaultScreenArea
    stateTracker: ru.mkilord.colortomqttapp.core.tracker.ToleranceColorStateTracker
    sensitivity: 30 #min 0 max 100
    hueTolerance: 0.2
    saturationTolerance: 0.15
    brightnessTolerance: 0.06

    modifyHue: 0
    modifySaturation: 0
    modifyBrightness: 0

    blackThreshold: 5 #%, ниже отправляется яркость 0
    grayThreshold: 12 #%, ниже отправляется насыщенность 0

    cellSize: 20

    #MQTT
    broker: ${MQTT_BROKER:tcp://localhost:1883}
    topic: ${MQTT_TOPIC:colorToMQTT}
    username: ${MQTT_USERNAME:}
    password: ${MQTT_PASSWORD:}

    minHUE: 0
    maxHUE: 360
    minSaturation: 0
    maxSaturation: 100
    minBrightness: 0
    maxBrightness: 100

